services:
  - type: web
    name: stock-analysis-backend
    env: node
    buildCommand: npm install --legacy-peer-deps
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3002
      - key: OPENAI_API_KEY
        sync: false
      - key: NEWS_API_KEY
        sync: false
    buildFilter:
      paths:
      - backend/**
      - package.json
      - render.yaml

  - type: web
    name: stock-analysis-frontend
    env: node
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm run preview
    rootDirectory: frontend
    envVars:
      - key: NODE_ENV
        value: production 