services:
  - type: web
    name: stock-analysis-backend
    env: node
    buildCommand: cd backend && npm install --legacy-peer-deps
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3002
      - key: OPENAI_API_KEY
        sync: false
      - key: NEWS_API_KEY
        sync: false
    healthCheckPath: /health
    healthCheckTimeout: 100
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 80
    buildFilter:
      paths:
      - backend/**
      - package.json
      - render.yaml

  - type: web
    name: stock-analysis-frontend
    env: node
    buildCommand: cd frontend && npm install --legacy-peer-deps && npm run build
    startCommand: cd frontend && npm run preview
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 80 